---
version: "3.7"
services:
  kasm:
    build: .
    image: ghcr.io/tetrabiodistributed/tetra-workspace-image:v0.1.0
    ports:
      - "6901:6901"
    environment:
      VNC_PW: password
    shm_size: '512m'
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    network_mode: bridge
    volumes:
      - type: bind
        source: ./kasm_user
        target: /home/kasm-user
    devices:
      - "/dev/ttyACM0"
    security_opt:
      - seccomp=unconfined
...
